helm_chart:
  name: cr.yandex/crp9ftr22d26age3hulg/yandex-cloud/csi-s3/csi-s3
  tag: 0.43.0
requirements:
  k8s_version: ">=1.13"
images:
  - full: images.registrar
  - full: images.provisioner
  - full: images.csi
user_values:
  - name: storageClass.create
    title:
      en: Create storage class
      ru: Создать класс хранения
    description:
      en: Specifies whether the storage class should be created
      ru: Выберите, чтобы создать новый S3-класс хранения при развёртывании приложения.
    boolean_value:
      default_value: true
  - name: secret.create
    title:
      en: Create secret
      ru: Создать секрет
    description:
      en: Specifies whether the secret should be created
      ru: Выберите, чтобы создать новый секрет для класса хранения при установке приложения, а не использовать существующий.
    boolean_value:
      default_value: true
  - name: secret.accessKey
    title:
      en: S3 Access Key ID
      ru: Идентификатор ключа S3
    description:
      en: S3 Access Key ID
      ru: Идентификатор ключа S3.
    string_value:
      default_value: ""
  - name: secret.secretKey
    title:
      en: S3 Secret Key
      ru: Секретный ключ S3
    description:
      en: S3 Secret Key
      ru: Секретный ключ S3.
    string_value:
      default_value: ""
      secret: true
  - name: storageClass.singleBucket
    title:
      en: Single S3 bucket for volumes
      ru: Общий бакет S3 для томов
    description:
      en: Single S3 bucket to use for all dynamically provisioned persistent volumes
      ru: Общий бакет S3, в котором будут создаваться все динамически распределяемые тома. Если пусто, под каждый том будет создаваться новый бакет.
    string_value:
      default_value: ""
  - name: secret.endpoint
    title:
      en: S3 endpoint
      ru: Адрес S3-сервиса
    description:
      en: S3 service endpoint to use
      ru: Адрес S3-сервиса, который будет использоваться.
    string_value:
      default_value: "https://storage.yandexcloud.net"
  - name: secret.region
    title:
      en: S3 region
      ru: S3 регион
    description:
      en: S3 service region to use
      ru: Регион используемого сервиса S3.
    string_value:
      default_value: ""
  - name: storageClass.mountOptions
    title:
      en: GeeseFS mount options
      ru: Опции монтирования GeeseFS
    description:
      en: GeeseFS mount options to use. Refer to `geesefs --help` command output for the whole list of options (https://github.com/yandex-cloud/geesefs).
      ru: Опции монтирования GeeseFS. Полный перечень и описание опций смотрите в выводе команды `geesefs --help` (https://github.com/yandex-cloud/geesefs).
    string_value:
      default_value: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666"
  - name: storageClass.reclaimPolicy
    title:
      en: Volume reclaim policy
      ru: Политика очистки томов
    description:
      en: Volume reclaim policy for the storage class (Retain or Delete)
      ru: Выберите политику очистки томов PersistentVolume при удалении PersistentVolumeClaim. Retain — сохранять том, Delete — удалять том.
    string_selector_value:
      default_value: Delete
      values:
        - Delete
        - Retain
  - name: storageClass.name
    title:
      en: Storage class name
      ru: Название класса хранения
    description:
      en: Name of the storage class that will be created
      ru: Название класса хранения, который будет создан при установке.
    string_value:
      default_value: csi-s3
  - name: secret.name
    title:
      en: Name of the secret
      ru: Название секрета
    description:
      en: Name of the secret to create or use for the storage class
      ru: Название секрета, который будет создан или использован для класса хранения.
    string_value:
      default_value: csi-s3-secret
  - name: tolerations.all
    title:
      en: Tolerate all taints
      ru: Игнорировать все политики taint
    description:
      en: Tolerate all taints by the CSI-S3 node driver (mounter)
      ru: Выберите, чтобы драйвер CSI, который монтирует файловую систему на узлах, игнорировал все политики taint для узлов кластера.
    boolean_value:
      default_value: false
